import "@/app/scss/globals.scss";
import Header from "@/components/Header";
import type { Metadata } from "next";
import Footer from "@/components/Footer";
import "aos/dist/aos.css";

export const metadata: Metadata = {
  title: "infivent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
